# Remova a linha "version: '3.8'" que estava aqui

services:
  # Serviço do Banco de Dados PostgreSQL
  postgres-db:
    image: postgres:16 # <-- 3. RECOMENDADO: Trave a versão (ex: 16)
    container_name: postgres_local_dev
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: my-auth-db 
    ports:
      - "5432:5432" 
    volumes:
      # 2. CORREÇÃO: Mude o caminho do volume.
      # A imagem agora gerencia as subpastas dentro de /var/lib/postgresql
      - postgres-data:/var/lib/postgresql 
    restart: unless-stopped

  # Serviço do pgAdmin (Interface Gráfica)
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_local_dev
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com 
      PGADMIN_DEFAULT_PASSWORD: admin 
    ports:
      - "8080:80" 
    depends_on:
      - postgres-db
    restart: unless-stopped

volumes:
  postgres-data:
    driver: local